import { getDb, upsertTitle, recordScrapeRun } from "../lib/db";

// Sample data so the UI (filters, top-10, suggestions) can be exercised
// before the real scrape pipeline is run. These are REAL 2025 releases,
// all with an IMDb rating of 7.0+ (per user requirement), spread across
// all 5 platforms — platform counts are uneven on purpose, since real
// per-platform quality/quantity isn't equal either. imdbId/posterUrl are
// left null: no verified-working OMDb key yet to confirm exact ids/poster
// URLs, and a wrong id/link would be worse than none. Ratings/runtimes are
// best-effort approximations; run `npm run scrape` with a valid
// OMDB_API_KEY to replace these with OMDb-verified values.
const SEED_TITLES = [
  // Netflix
  {
    imdbId: null,
    title: "Frankenstein",
    type: "movie" as const,
    year: 2025,
    genres: ["Drama", "Horror", "Sci-Fi"],
    runtimeMinutes: 149,
    imdbRating: 7.5,
    plot: "Guillermo del Toro's retelling of Mary Shelley's story of a scientist and the creature he brings to life.",
    posterUrl: null,
    releasedDate: "2025-11-07",
    addedToPlatformDate: "2026-07-01",
    platforms: ["netflix" as const],
  },
  {
    imdbId: null,
    title: "K-Pop Demon Hunters",
    type: "movie" as const,
    year: 2025,
    genres: ["Animation", "Action", "Comedy", "Fantasy", "Musical"],
    runtimeMinutes: 96,
    imdbRating: 7.8,
    plot: "A K-pop girl group secretly moonlights as demon hunters protecting their fans from supernatural threats.",
    posterUrl: null,
    releasedDate: "2025-06-20",
    addedToPlatformDate: "2026-07-03",
    platforms: ["netflix" as const],
  },
  // Disney+
  {
    imdbId: null,
    title: "Thunderbolts*",
    type: "movie" as const,
    year: 2025,
    genres: ["Action", "Adventure", "Sci-Fi"],
    runtimeMinutes: 127,
    imdbRating: 7.6,
    plot: "A group of antiheroes and former villains are thrown together on a dangerous mission.",
    posterUrl: null,
    releasedDate: "2025-05-02",
    addedToPlatformDate: "2026-07-02",
    platforms: ["disney_plus" as const],
  },
  // HBO Max
  {
    imdbId: null,
    title: "Sinners",
    type: "movie" as const,
    year: 2025,
    genres: ["Horror", "Thriller"],
    runtimeMinutes: 137,
    imdbRating: 7.8,
    plot: "Twin brothers return to their Mississippi hometown to start over, only to find that evil has followed them.",
    posterUrl: null,
    releasedDate: "2025-04-18",
    addedToPlatformDate: "2026-07-04",
    platforms: ["hbo_max" as const],
  },
  {
    imdbId: null,
    title: "Mickey 17",
    type: "movie" as const,
    year: 2025,
    genres: ["Comedy", "Sci-Fi"],
    runtimeMinutes: 137,
    imdbRating: 7.0,
    plot: "An expendable employee on a space colony is reprinted with a new body each time he dies, until things go wrong.",
    posterUrl: null,
    releasedDate: "2025-03-07",
    addedToPlatformDate: "2026-07-06",
    platforms: ["hbo_max" as const],
  },
  {
    imdbId: null,
    title: "One Battle After Another",
    type: "movie" as const,
    year: 2025,
    genres: ["Action", "Comedy", "Drama"],
    runtimeMinutes: 162,
    imdbRating: 8.0,
    plot: "A former revolutionary must resurface after years in hiding when an old enemy re-enters his life.",
    posterUrl: null,
    releasedDate: "2025-09-26",
    addedToPlatformDate: "2026-07-08",
    platforms: ["hbo_max" as const],
  },
  {
    imdbId: null,
    title: "Weapons",
    type: "movie" as const,
    year: 2025,
    genres: ["Horror", "Mystery"],
    runtimeMinutes: 128,
    imdbRating: 7.5,
    plot: "When almost all the children from one class vanish without a trace on the same night, a community is torn apart.",
    posterUrl: null,
    releasedDate: "2025-08-08",
    addedToPlatformDate: "2026-07-10",
    platforms: ["hbo_max" as const],
  },
  // Videoland
  {
    imdbId: null,
    title: "Wicked: Part Two",
    type: "movie" as const,
    year: 2025,
    genres: ["Fantasy", "Musical", "Romance"],
    runtimeMinutes: 137,
    imdbRating: 7.5,
    plot: "The continuation of Elphaba and Glinda's story as their paths diverge in the land of Oz.",
    posterUrl: null,
    releasedDate: "2025-11-21",
    addedToPlatformDate: "2026-07-09",
    platforms: ["videoland" as const],
  },
  {
    imdbId: null,
    title: "How to Train Your Dragon",
    type: "movie" as const,
    year: 2025,
    genres: ["Adventure", "Family", "Fantasy"],
    runtimeMinutes: 125,
    imdbRating: 7.3,
    plot: "A live-action retelling of a young Viking who befriends a dragon considered a mortal enemy by his village.",
    posterUrl: null,
    releasedDate: "2025-06-13",
    addedToPlatformDate: "2026-07-11",
    platforms: ["videoland" as const],
  },
  {
    imdbId: null,
    title: "Bugonia",
    type: "movie" as const,
    year: 2025,
    genres: ["Comedy", "Drama", "Sci-Fi"],
    runtimeMinutes: 118,
    imdbRating: 7.3,
    plot: "Two conspiracy-obsessed men kidnap a corporate CEO they believe to be an alien.",
    posterUrl: null,
    releasedDate: "2025-10-24",
    addedToPlatformDate: "2026-07-12",
    platforms: ["videoland" as const],
  },
  // --- Series ---
  {
    imdbId: null,
    title: "The Night Agent",
    type: "series" as const,
    year: 2025,
    genres: ["Action", "Drama", "Thriller"],
    runtimeMinutes: 45,
    imdbRating: 7.5,
    plot: "A low-level FBI agent working in the White House basement is thrust into a conspiracy.",
    posterUrl: null,
    releasedDate: "2025-01-23",
    addedToPlatformDate: "2026-07-01",
    platforms: ["netflix" as const],
  },
  {
    imdbId: null,
    title: "Devil May Cry",
    type: "series" as const,
    year: 2025,
    genres: ["Animation", "Action", "Fantasy"],
    runtimeMinutes: 30,
    imdbRating: 7.0,
    plot: "Half-demon mercenary Dante battles demonic forces threatening to break into the human world.",
    posterUrl: null,
    releasedDate: "2025-04-03",
    addedToPlatformDate: "2026-07-05",
    platforms: ["netflix" as const],
  },
  {
    imdbId: null,
    title: "Reacher",
    type: "series" as const,
    year: 2025,
    genres: ["Action", "Crime", "Drama"],
    runtimeMinutes: 50,
    imdbRating: 8.5,
    plot: "Jack Reacher investigates the murder of his old army unit's members one by one.",
    posterUrl: null,
    releasedDate: "2025-02-20",
    addedToPlatformDate: "2026-07-03",
    platforms: ["prime_video" as const],
  },
  {
    imdbId: null,
    title: "Fallout",
    type: "series" as const,
    year: 2025,
    genres: ["Action", "Adventure", "Drama"],
    runtimeMinutes: 60,
    imdbRating: 8.0,
    plot: "Season two: in a world destroyed by nuclear war, survivors emerge from underground vaults to face new threats.",
    posterUrl: null,
    releasedDate: "2025-12-17",
    addedToPlatformDate: "2026-07-08",
    platforms: ["prime_video" as const],
  },
  {
    imdbId: null,
    title: "Andor",
    type: "series" as const,
    year: 2025,
    genres: ["Action", "Adventure", "Drama"],
    runtimeMinutes: 45,
    imdbRating: 9.0,
    plot: "Cassian Andor's journey to becoming a rebel spy against the Galactic Empire reaches its conclusion.",
    posterUrl: null,
    releasedDate: "2025-04-22",
    addedToPlatformDate: "2026-07-02",
    platforms: ["disney_plus" as const],
  },
  {
    imdbId: null,
    title: "Daredevil: Born Again",
    type: "series" as const,
    year: 2025,
    genres: ["Action", "Crime", "Drama"],
    runtimeMinutes: 50,
    imdbRating: 7.5,
    plot: "Matt Murdock and Wilson Fisk's paths collide again as one pursues justice and the other power.",
    posterUrl: null,
    releasedDate: "2025-03-04",
    addedToPlatformDate: "2026-07-07",
    platforms: ["disney_plus" as const],
  },
  {
    imdbId: null,
    title: "The Last of Us",
    type: "series" as const,
    year: 2025,
    genres: ["Action", "Adventure", "Drama"],
    runtimeMinutes: 55,
    imdbRating: 7.5,
    plot: "Season two: Joel and Ellie are pulled apart as the world they've fought to survive spirals further.",
    posterUrl: null,
    releasedDate: "2025-04-13",
    addedToPlatformDate: "2026-07-04",
    platforms: ["hbo_max" as const],
  },
  {
    imdbId: null,
    title: "The White Lotus",
    type: "series" as const,
    year: 2025,
    genres: ["Comedy", "Drama"],
    runtimeMinutes: 60,
    imdbRating: 7.8,
    plot: "Season three: wealthy guests at a luxury resort in Thailand navigate secrets, tension and status.",
    posterUrl: null,
    releasedDate: "2025-02-16",
    addedToPlatformDate: "2026-07-06",
    platforms: ["hbo_max" as const],
  },
  {
    imdbId: null,
    title: "Task",
    type: "series" as const,
    year: 2025,
    genres: ["Crime", "Drama", "Thriller"],
    runtimeMinutes: 55,
    imdbRating: 7.8,
    plot: "An FBI agent leads a task force investigating a string of home-invasion robberies with a surprising connection.",
    posterUrl: null,
    releasedDate: "2025-09-07",
    addedToPlatformDate: "2026-07-09",
    platforms: ["hbo_max" as const],
  },
  {
    imdbId: null,
    title: "Poker Face",
    type: "series" as const,
    year: 2025,
    genres: ["Comedy", "Crime", "Mystery"],
    runtimeMinutes: 50,
    imdbRating: 7.8,
    plot: "Human lie-detector Charlie Cale drifts across the country solving crimes wherever she lands.",
    posterUrl: null,
    releasedDate: "2025-05-08",
    addedToPlatformDate: "2026-07-10",
    platforms: ["videoland" as const],
  },
];

function main() {
  const db = getDb();
  // Clear any previous seed/scrape data so re-running this script doesn't
  // leave stale titles from earlier iterations mixed in.
  db.exec(`DELETE FROM title_platforms; DELETE FROM titles;`);
  for (const t of SEED_TITLES) {
    upsertTitle(t);
  }
  recordScrapeRun("success", SEED_TITLES.length, "seed data (2025 titles, 7.0+ rating)");
  console.log(`Seeded ${SEED_TITLES.length} titles.`);
}

main();
