import { getDb, upsertTitle, recordScrapeRun } from "../lib/db";

// Sample data so the UI (filters, top-10, suggestions) can be exercised
// before OMDB_API_KEY / real JustWatch scraping is set up.
// 10 movies + 10 series, spread across all 5 platforms and several genres/
// runtimes, so filters have enough data to actually filter against.
const SEED_TITLES = [
  {
    imdbId: "tt0000001",
    title: "Nachtwacht",
    type: "movie" as const,
    year: 2026,
    genres: ["Thriller", "Drama"],
    runtimeMinutes: 118,
    imdbRating: 8.1,
    plot: "Een rechercheur onderzoekt een reeks verdwijningen in Rotterdam.",
    posterUrl: null,
    releasedDate: "2026-07-01",
    addedToPlatformDate: "2026-07-01",
    platforms: ["netflix" as const],
  },
  {
    imdbId: "tt0000002",
    title: "Zonlicht",
    type: "movie" as const,
    year: 2026,
    genres: ["Comedy", "Romance"],
    runtimeMinutes: 95,
    imdbRating: 7.4,
    plot: "Twee vreemden delen een zomer in Zeeland.",
    posterUrl: null,
    releasedDate: "2026-07-05",
    addedToPlatformDate: "2026-07-05",
    platforms: ["prime_video" as const],
  },
  {
    imdbId: "tt0000005",
    title: "Sterrenreis: Ontwaken",
    type: "movie" as const,
    year: 2026,
    genres: ["Sci-Fi", "Action"],
    runtimeMinutes: 142,
    imdbRating: 8.3,
    plot: "Een bemanning ontdekt een signaal buiten het zonnestelsel.",
    posterUrl: null,
    releasedDate: "2026-07-08",
    addedToPlatformDate: "2026-07-08",
    platforms: ["disney_plus" as const],
  },
  {
    imdbId: "tt0000006",
    title: "De Laatste Trein",
    type: "movie" as const,
    year: 2026,
    genres: ["Thriller", "Action"],
    runtimeMinutes: 104,
    imdbRating: 7.8,
    plot: "Een gijzeling op de nachttrein Amsterdam-Berlijn.",
    posterUrl: null,
    releasedDate: "2026-07-03",
    addedToPlatformDate: "2026-07-03",
    platforms: ["hbo_max" as const],
  },
  {
    imdbId: "tt0000007",
    title: "Kroeglegendes",
    type: "movie" as const,
    year: 2026,
    genres: ["Comedy"],
    runtimeMinutes: 88,
    imdbRating: 6.9,
    plot: "Vier vrienden proberen hun stamkroeg te redden.",
    posterUrl: null,
    releasedDate: "2026-07-12",
    addedToPlatformDate: "2026-07-12",
    platforms: ["videoland" as const],
  },
  {
    imdbId: "tt0000008",
    title: "Onder Water",
    type: "movie" as const,
    year: 2026,
    genres: ["Drama", "Documentaire"],
    runtimeMinutes: 76,
    imdbRating: 8.5,
    plot: "Een duikteam brengt een verzonken dorp in kaart.",
    posterUrl: null,
    releasedDate: "2026-06-30",
    addedToPlatformDate: "2026-06-30",
    platforms: ["netflix" as const],
  },
  {
    imdbId: "tt0000009",
    title: "Vuurtoren",
    type: "movie" as const,
    year: 2026,
    genres: ["Horror", "Thriller"],
    runtimeMinutes: 99,
    imdbRating: 7.2,
    plot: "Twee vuurtorenwachters raken geïsoleerd door een storm.",
    posterUrl: null,
    releasedDate: "2026-07-14",
    addedToPlatformDate: "2026-07-14",
    platforms: ["prime_video" as const],
  },
  {
    imdbId: "tt0000010",
    title: "Sprong",
    type: "movie" as const,
    year: 2026,
    genres: ["Action", "Sci-Fi"],
    runtimeMinutes: 131,
    imdbRating: 7.6,
    plot: "Een piloot test een experimentele tijdmachine.",
    posterUrl: null,
    releasedDate: "2026-07-02",
    addedToPlatformDate: "2026-07-02",
    platforms: ["disney_plus" as const],
  },
  {
    imdbId: "tt0000011",
    title: "Wintergasten",
    type: "movie" as const,
    year: 2026,
    genres: ["Drama", "Romance"],
    runtimeMinutes: 109,
    imdbRating: 8.0,
    plot: "Een familie herenigt op een besneeuwde boerderij.",
    posterUrl: null,
    releasedDate: "2026-06-28",
    addedToPlatformDate: "2026-06-28",
    platforms: ["hbo_max" as const],
  },
  {
    imdbId: "tt0000012",
    title: "Bliksemschicht",
    type: "movie" as const,
    year: 2026,
    genres: ["Action", "Comedy"],
    runtimeMinutes: 112,
    imdbRating: 7.1,
    plot: "Een koerier belandt per ongeluk in een undercoveroperatie.",
    posterUrl: null,
    releasedDate: "2026-07-11",
    addedToPlatformDate: "2026-07-11",
    platforms: ["videoland" as const],
  },
  {
    imdbId: "tt0000003",
    title: "IJzeren Kroon",
    type: "series" as const,
    year: 2026,
    genres: ["Fantasy", "Drama"],
    runtimeMinutes: 55,
    imdbRating: 8.7,
    plot: "Een middeleeuws rijk valt uiteen na de dood van de koning.",
    posterUrl: null,
    releasedDate: "2026-06-25",
    addedToPlatformDate: "2026-06-25",
    platforms: ["hbo_max" as const],
  },
  {
    imdbId: "tt0000004",
    title: "Lachspiegel",
    type: "series" as const,
    year: 2026,
    genres: ["Comedy"],
    runtimeMinutes: 25,
    imdbRating: 7.9,
    plot: "Een sketchshow over het Nederlandse kantoorleven.",
    posterUrl: null,
    releasedDate: "2026-07-10",
    addedToPlatformDate: "2026-07-10",
    platforms: ["videoland" as const],
  },
  {
    imdbId: "tt0000013",
    title: "Codewoord Meeuw",
    type: "series" as const,
    year: 2026,
    genres: ["Thriller", "Drama"],
    runtimeMinutes: 48,
    imdbRating: 8.2,
    plot: "Een inlichtingendienst jaagt op een mol binnen de eigen organisatie.",
    posterUrl: null,
    releasedDate: "2026-07-04",
    addedToPlatformDate: "2026-07-04",
    platforms: ["netflix" as const],
  },
  {
    imdbId: "tt0000014",
    title: "Duinvolk",
    type: "series" as const,
    year: 2026,
    genres: ["Sci-Fi", "Drama"],
    runtimeMinutes: 52,
    imdbRating: 8.6,
    plot: "Kolonisten vechten om te overleven op een woestijnplaneet.",
    posterUrl: null,
    releasedDate: "2026-06-27",
    addedToPlatformDate: "2026-06-27",
    platforms: ["disney_plus" as const],
  },
  {
    imdbId: "tt0000015",
    title: "Buurtwacht",
    type: "series" as const,
    year: 2026,
    genres: ["Comedy", "Drama"],
    runtimeMinutes: 30,
    imdbRating: 7.3,
    plot: "Een groep buren start een chaotisch buurtpreventieteam.",
    posterUrl: null,
    releasedDate: "2026-07-13",
    addedToPlatformDate: "2026-07-13",
    platforms: ["prime_video" as const],
  },
  {
    imdbId: "tt0000016",
    title: "De Rechtbank",
    type: "series" as const,
    year: 2026,
    genres: ["Drama"],
    runtimeMinutes: 45,
    imdbRating: 8.0,
    plot: "Een jonge advocaat neemt een onmogelijke zaak aan.",
    posterUrl: null,
    releasedDate: "2026-07-06",
    addedToPlatformDate: "2026-07-06",
    platforms: ["hbo_max" as const],
  },
  {
    imdbId: "tt0000017",
    title: "Spooklijn",
    type: "series" as const,
    year: 2026,
    genres: ["Horror", "Thriller"],
    runtimeMinutes: 42,
    imdbRating: 7.5,
    plot: "Een verlaten metrolijn blijkt niet zo verlaten als gedacht.",
    posterUrl: null,
    releasedDate: "2026-07-09",
    addedToPlatformDate: "2026-07-09",
    platforms: ["netflix" as const],
  },
  {
    imdbId: "tt0000018",
    title: "Marktplein",
    type: "series" as const,
    year: 2026,
    genres: ["Comedy", "Romance"],
    runtimeMinutes: 28,
    imdbRating: 7.0,
    plot: "Twee marktkraamhouders concurreren én worden verliefd.",
    posterUrl: null,
    releasedDate: "2026-07-15",
    addedToPlatformDate: "2026-07-15",
    platforms: ["videoland" as const],
  },
  {
    imdbId: "tt0000019",
    title: "Poolexpeditie",
    type: "series" as const,
    year: 2026,
    genres: ["Documentaire", "Drama"],
    runtimeMinutes: 50,
    imdbRating: 8.4,
    plot: "Een team wetenschappers raakt geïsoleerd op Antarctica.",
    posterUrl: null,
    releasedDate: "2026-06-29",
    addedToPlatformDate: "2026-06-29",
    platforms: ["disney_plus" as const],
  },
  {
    imdbId: "tt0000020",
    title: "Zwarte Doos",
    type: "series" as const,
    year: 2026,
    genres: ["Thriller", "Sci-Fi"],
    runtimeMinutes: 47,
    imdbRating: 7.7,
    plot: "Onderzoekers ontcijferen de flightrecorder van een verdwenen vliegtuig.",
    posterUrl: null,
    releasedDate: "2026-07-07",
    addedToPlatformDate: "2026-07-07",
    platforms: ["prime_video" as const],
  },
];

function main() {
  getDb();
  for (const t of SEED_TITLES) {
    upsertTitle(t);
  }
  recordScrapeRun("success", SEED_TITLES.length, "seed data");
  console.log(`Seeded ${SEED_TITLES.length} titles.`);
}

main();
