import { getDb, upsertTitle, recordScrapeRun } from "../lib/db";

// Sample data so the UI (filters, top-10, suggestions) can be exercised
// before the real scrape pipeline is run. These are REAL, well-known
// titles (not invented placeholders) so they're actually searchable/
// verifiable on IMDb — imdbId is left null because we don't have a
// verified-correct id for each without calling OMDb, and a wrong id would
// be worse than none. addedToPlatformDate is set to a recent date purely
// to populate the "last month" view; original release year is kept accurate.
const SEED_TITLES = [
  // Netflix
  {
    imdbId: null,
    title: "Extraction 2",
    type: "movie" as const,
    year: 2023,
    genres: ["Action", "Thriller"],
    runtimeMinutes: 122,
    imdbRating: 6.9,
    plot: "Tyler Rake takes on a new mission to extract a family from a Georgian prison.",
    posterUrl: null,
    releasedDate: "2023-06-16",
    addedToPlatformDate: "2026-07-01",
    platforms: ["netflix" as const],
  },
  {
    imdbId: null,
    title: "Glass Onion: A Knives Out Mystery",
    type: "movie" as const,
    year: 2022,
    genres: ["Comedy", "Crime", "Drama"],
    runtimeMinutes: 139,
    imdbRating: 7.1,
    plot: "Detective Benoit Blanc travels to Greece to solve a new mystery.",
    posterUrl: null,
    releasedDate: "2022-12-23",
    addedToPlatformDate: "2026-07-03",
    platforms: ["netflix" as const],
  },
  // Prime Video
  {
    imdbId: null,
    title: "The Tomorrow War",
    type: "movie" as const,
    year: 2021,
    genres: ["Action", "Sci-Fi"],
    runtimeMinutes: 138,
    imdbRating: 6.5,
    plot: "A soldier is drafted to fight in a future war against an alien species.",
    posterUrl: null,
    releasedDate: "2021-07-02",
    addedToPlatformDate: "2026-07-05",
    platforms: ["prime_video" as const],
  },
  {
    imdbId: null,
    title: "Saltburn",
    type: "movie" as const,
    year: 2023,
    genres: ["Drama", "Thriller"],
    runtimeMinutes: 131,
    imdbRating: 7.1,
    plot: "A student at Oxford becomes entangled with a classmate's wealthy, eccentric family.",
    posterUrl: null,
    releasedDate: "2023-11-17",
    addedToPlatformDate: "2026-07-08",
    platforms: ["prime_video" as const],
  },
  // Disney+
  {
    imdbId: null,
    title: "Guardians of the Galaxy Vol. 3",
    type: "movie" as const,
    year: 2023,
    genres: ["Action", "Adventure", "Comedy"],
    runtimeMinutes: 150,
    imdbRating: 7.9,
    plot: "Peter Quill rallies his team to defend the universe and one of their own.",
    posterUrl: null,
    releasedDate: "2023-05-05",
    addedToPlatformDate: "2026-07-02",
    platforms: ["disney_plus" as const],
  },
  {
    imdbId: null,
    title: "Elemental",
    type: "movie" as const,
    year: 2023,
    genres: ["Animation", "Comedy", "Family"],
    runtimeMinutes: 101,
    imdbRating: 6.9,
    plot: "In a city where fire, water, land and air residents live together, a fire girl and a water guy discover something elemental.",
    posterUrl: null,
    releasedDate: "2023-06-16",
    addedToPlatformDate: "2026-07-10",
    platforms: ["disney_plus" as const],
  },
  // HBO Max
  {
    imdbId: null,
    title: "Dune: Part Two",
    type: "movie" as const,
    year: 2024,
    genres: ["Action", "Adventure", "Drama"],
    runtimeMinutes: 166,
    imdbRating: 8.5,
    plot: "Paul Atreides unites with the Fremen to seek revenge against the conspirators who destroyed his family.",
    posterUrl: null,
    releasedDate: "2024-03-01",
    addedToPlatformDate: "2026-07-04",
    platforms: ["hbo_max" as const],
  },
  {
    imdbId: null,
    title: "Barbie",
    type: "movie" as const,
    year: 2023,
    genres: ["Adventure", "Comedy", "Fantasy"],
    runtimeMinutes: 114,
    imdbRating: 6.9,
    plot: "Barbie and Ken venture from Barbieland to the real world.",
    posterUrl: null,
    releasedDate: "2023-07-21",
    addedToPlatformDate: "2026-07-06",
    platforms: ["hbo_max" as const],
  },
  // Videoland
  {
    imdbId: null,
    title: "Fast X",
    type: "movie" as const,
    year: 2023,
    genres: ["Action", "Crime", "Thriller"],
    runtimeMinutes: 141,
    imdbRating: 5.8,
    plot: "Dom Toretto and his family face their most lethal opponent yet.",
    posterUrl: null,
    releasedDate: "2023-05-19",
    addedToPlatformDate: "2026-07-09",
    platforms: ["videoland" as const],
  },
  {
    imdbId: null,
    title: "Cocaine Bear",
    type: "movie" as const,
    year: 2023,
    genres: ["Comedy", "Crime", "Thriller"],
    runtimeMinutes: 95,
    imdbRating: 5.9,
    plot: "An oddball group converges on a Georgia forest after $2 million of missing cocaine and a very hungry black bear.",
    posterUrl: null,
    releasedDate: "2023-02-24",
    addedToPlatformDate: "2026-07-11",
    platforms: ["videoland" as const],
  },
  // --- Series ---
  {
    imdbId: null,
    title: "Wednesday",
    type: "series" as const,
    year: 2022,
    genres: ["Comedy", "Fantasy", "Horror"],
    runtimeMinutes: 50,
    imdbRating: 8.1,
    plot: "Wednesday Addams navigates her years at Nevermore Academy while solving a supernatural mystery.",
    posterUrl: null,
    releasedDate: "2022-11-23",
    addedToPlatformDate: "2026-07-01",
    platforms: ["netflix" as const],
  },
  {
    imdbId: null,
    title: "The Crown",
    type: "series" as const,
    year: 2023,
    genres: ["Drama", "History"],
    runtimeMinutes: 55,
    imdbRating: 8.6,
    plot: "Follows the political rivalries and romance of Queen Elizabeth II's reign.",
    posterUrl: null,
    releasedDate: "2023-12-14",
    addedToPlatformDate: "2026-07-05",
    platforms: ["netflix" as const],
  },
  {
    imdbId: null,
    title: "The Boys",
    type: "series" as const,
    year: 2019,
    genres: ["Action", "Comedy", "Crime"],
    runtimeMinutes: 60,
    imdbRating: 8.7,
    plot: "A group of vigilantes set out to take down corrupt superheroes.",
    posterUrl: null,
    releasedDate: "2019-07-26",
    addedToPlatformDate: "2026-07-03",
    platforms: ["prime_video" as const],
  },
  {
    imdbId: null,
    title: "Fallout",
    type: "series" as const,
    year: 2024,
    genres: ["Action", "Adventure", "Drama"],
    runtimeMinutes: 60,
    imdbRating: 8.3,
    plot: "In a world destroyed by nuclear war, survivors emerge from underground vaults.",
    posterUrl: null,
    releasedDate: "2024-04-10",
    addedToPlatformDate: "2026-07-08",
    platforms: ["prime_video" as const],
  },
  {
    imdbId: null,
    title: "Loki",
    type: "series" as const,
    year: 2021,
    genres: ["Action", "Adventure", "Fantasy"],
    runtimeMinutes: 50,
    imdbRating: 8.2,
    plot: "Loki is recruited by the mysterious Time Variance Authority after stealing the Tesseract.",
    posterUrl: null,
    releasedDate: "2021-06-09",
    addedToPlatformDate: "2026-07-02",
    platforms: ["disney_plus" as const],
  },
  {
    imdbId: null,
    title: "Ahsoka",
    type: "series" as const,
    year: 2023,
    genres: ["Action", "Adventure", "Fantasy"],
    runtimeMinutes: 45,
    imdbRating: 7.3,
    plot: "Ahsoka Tano investigates an emerging threat to a vulnerable galaxy.",
    posterUrl: null,
    releasedDate: "2023-08-22",
    addedToPlatformDate: "2026-07-07",
    platforms: ["disney_plus" as const],
  },
  {
    imdbId: null,
    title: "The Last of Us",
    type: "series" as const,
    year: 2023,
    genres: ["Action", "Adventure", "Drama"],
    runtimeMinutes: 50,
    imdbRating: 8.8,
    plot: "Twenty years after a fungal outbreak, Joel and Ellie journey across a devastated United States.",
    posterUrl: null,
    releasedDate: "2023-01-15",
    addedToPlatformDate: "2026-07-04",
    platforms: ["hbo_max" as const],
  },
  {
    imdbId: null,
    title: "House of the Dragon",
    type: "series" as const,
    year: 2022,
    genres: ["Action", "Adventure", "Drama"],
    runtimeMinutes: 60,
    imdbRating: 8.4,
    plot: "The Targaryen civil war begins over the succession to the Iron Throne.",
    posterUrl: null,
    releasedDate: "2022-08-21",
    addedToPlatformDate: "2026-07-06",
    platforms: ["hbo_max" as const],
  },
  {
    imdbId: null,
    title: "The Office",
    type: "series" as const,
    year: 2005,
    genres: ["Comedy"],
    runtimeMinutes: 22,
    imdbRating: 9.0,
    plot: "A mockumentary on a group of typical office workers at a paper sales company.",
    posterUrl: null,
    releasedDate: "2005-03-24",
    addedToPlatformDate: "2026-07-10",
    platforms: ["videoland" as const],
  },
  {
    imdbId: null,
    title: "Suits",
    type: "series" as const,
    year: 2011,
    genres: ["Drama"],
    runtimeMinutes: 44,
    imdbRating: 8.5,
    plot: "A talented college dropout becomes a fake lawyer's associate at a top New York law firm.",
    posterUrl: null,
    releasedDate: "2011-06-23",
    addedToPlatformDate: "2026-07-12",
    platforms: ["videoland" as const],
  },
];

function main() {
  const db = getDb();
  // Clear any previous seed/scrape data so re-running this script doesn't
  // leave stale/fictional titles (e.g. earlier placeholder data) mixed in.
  db.exec(`DELETE FROM title_platforms; DELETE FROM titles;`);
  for (const t of SEED_TITLES) {
    upsertTitle(t);
  }
  recordScrapeRun("success", SEED_TITLES.length, "seed data (real titles)");
  console.log(`Seeded ${SEED_TITLES.length} titles.`);
}

main();
